// ============================================================================
// config/dict-default.js
//
// Дефолтный словарь турниров.
// Формат записи: { typeid, name, level, type }
//   typeid — 1, 2, 3, 7, 9, 13 — это 6 регулярных категорий.
//            typeid=7 (Призовые) теперь тоже считается регулярной.
//   name   — нормализованное имя (lowercase, без римского суффикса,
//            без префикса категории, без даты)
//   level  — '5' | '10-15' | 'unlimited' | ...
//   type   — 'usual' (только основные) | 'all' (с экстра-типами)
//
// version: 2 — переход с массива [typeid, name, italic, typeField]
// на объекты с готовыми level и type.
// ============================================================================

window.GH = window.GH || {};

window.GH.defaultDict = {
    version: 2,
    generatedAt: '2026-09-16',
    entries: [

        // ------------------------------------------------------------------
        // Плебейские (typeid 1) — 14
        // ------------------------------------------------------------------
        { typeid: 1, name: 'беллоновы игры',   level: '15',    type: 'usual' },
        { typeid: 1, name: 'весперовы игры',   level: '10-15', type: 'usual' },
        { typeid: 1, name: 'игры граций',      level: '12',    type: 'usual' },
        { typeid: 1, name: 'игры минервы',     level: '15',    type: 'usual' },
        { typeid: 1, name: 'игры ноны',        level: '15',    type: 'usual' },
        { typeid: 1, name: 'игры теллуры',     level: '15',    type: 'usual' },
        { typeid: 1, name: 'мортовы игры',     level: '15',    type: 'usual' },
        { typeid: 1, name: 'турнир атласа',    level: '8',     type: 'usual' },
        { typeid: 1, name: 'турнир бахуса',    level: '10',    type: 'usual' },
        { typeid: 1, name: 'турнир весты',     level: '11-15', type: 'usual' },
        { typeid: 1, name: 'турнир децимы',    level: '10',    type: 'usual' },
        { typeid: 1, name: 'турнир помоны',    level: '5',     type: 'usual' },
        { typeid: 1, name: 'турнир фавония',   level: '10',    type: 'usual' },
        { typeid: 1, name: 'турнир цереры',    level: '20',    type: 'usual' },

        // ------------------------------------------------------------------
        // Турниры новичков (typeid 2) — 12
        // ------------------------------------------------------------------
        { typeid: 2, name: 'игры виктории',         level: '10', type: 'usual' },
        { typeid: 2, name: 'игры нериены',          level: '10', type: 'usual' },
        { typeid: 2, name: 'игры соспиты',          level: '8',  type: 'usual' },
        { typeid: 2, name: 'игры термины',          level: '6',  type: 'usual' },
        { typeid: 2, name: 'игры фурий',            level: '5',  type: 'usual' },
        { typeid: 2, name: 'каменовы игры',         level: '8',  type: 'usual' },
        { typeid: 2, name: 'малые игры прозерпины', level: '4',  type: 'usual' },
        { typeid: 2, name: 'малые игры фортуны',    level: '7',  type: 'usual' },
        { typeid: 2, name: 'малый турнир меркурия', level: '5',  type: 'usual' },
        { typeid: 2, name: 'турнир геркулеса',      level: '8',  type: 'usual' },
        { typeid: 2, name: 'турнир салации',        level: '10', type: 'usual' },
        { typeid: 2, name: 'турнир ютурны',         level: '10', type: 'usual' },

        // ------------------------------------------------------------------
        // Сенаторские (typeid 3) — 27
        // ------------------------------------------------------------------
        { typeid: 3, name: 'большие игры вертумна',  level: '8',         type: 'usual' },
        { typeid: 3, name: 'большие игры виктории',  level: '30',        type: 'usual' },
        { typeid: 3, name: 'большие каменовы игры',  level: '5',         type: 'usual' },
        { typeid: 3, name: 'игры единорога',         level: 'unlimited', type: 'all'   },
        { typeid: 3, name: 'игры лаверны',           level: '45',        type: 'usual' },
        { typeid: 3, name: 'игры легионеров',        level: '40',        type: 'all'   },
        { typeid: 3, name: 'игры медузы горгоны',    level: '65',        type: 'all'   },
        { typeid: 3, name: 'игры нептуна',           level: '60',        type: 'all'   },
        { typeid: 3, name: 'игры нокс',              level: '45',        type: 'all'   },
        { typeid: 3, name: 'игры оркуса',            level: '8',         type: 'all'   },
        { typeid: 3, name: 'игры рудиуса',           level: '40',        type: 'usual' },
        { typeid: 3, name: 'игры феникса',           level: '50',        type: 'usual' },
        { typeid: 3, name: 'новый римский',          level: '25',        type: 'usual' },
        { typeid: 3, name: 'турнир гения',           level: '10',        type: 'usual' },
        { typeid: 3, name: 'турнир домициана',       level: '15',        type: 'usual' },
        { typeid: 3, name: 'турнир дракона',         level: 'unlimited', type: 'usual' },
        { typeid: 3, name: 'турнир калигулы',        level: '25',        type: 'all'   },
        { typeid: 3, name: 'турнир каллисто',        level: '35',        type: 'usual' },
        { typeid: 3, name: 'турнир луны',            level: '10',        type: 'all'   },
        { typeid: 3, name: 'турнир люцифера',        level: '15',        type: 'all'   },
        { typeid: 3, name: 'турнир майи',            level: '20',        type: 'usual' },
        { typeid: 3, name: 'турнир марка аврелия',   level: '30',        type: 'all'   },
        { typeid: 3, name: 'турнир марса',           level: '50',        type: 'all'   },
        { typeid: 3, name: 'турнир морта',           level: '55',        type: 'all'   },
        { typeid: 3, name: 'турнир оковы гефеста',   level: '55',        type: 'usual' },
        { typeid: 3, name: 'турнир прометея',        level: '35',        type: 'all'   },
        { typeid: 3, name: 'турнир фаммы',           level: '20',        type: 'all'   },

        // ------------------------------------------------------------------
        // Призовые (typeid 7) — 23 (это регулярная категория с этой версии)
        // ------------------------------------------------------------------
        { typeid: 7, name: '10: призовой турнир', level: '10',        type: 'usual' },
        { typeid: 7, name: '15: призовой турнир', level: '15',        type: 'usual' },
        { typeid: 7, name: '20: призовой турнир', level: '20',        type: 'usual' },
        { typeid: 7, name: '25: призовой турнир', level: '25',        type: 'usual' },
        { typeid: 7, name: '30: призовой турнир', level: '30',        type: 'usual' },
        { typeid: 7, name: '35: призовой турнир', level: '35',        type: 'usual' },
        { typeid: 7, name: '40: призовой турнир', level: '40',        type: 'usual' },
        { typeid: 7, name: '45: призовой турнир', level: '45',        type: 'usual' },
        { typeid: 7, name: '50: призовой турнир', level: '50',        type: 'usual' },
        { typeid: 7, name: '55: призовой турнир', level: '55',        type: 'usual' },
        { typeid: 7, name: 'призовой турнир',     level: 'unlimited', type: 'usual' },
        { typeid: 7, name: 'сундук',              level: 'unlimited', type: 'usual' },
        { typeid: 7, name: 'сундук-10',           level: '10',        type: 'usual' },
        { typeid: 7, name: 'сундук-15',           level: '15',        type: 'usual' },
        { typeid: 7, name: 'сундук-20',           level: '20',        type: 'usual' },
        { typeid: 7, name: 'сундук-25',           level: '25',        type: 'usual' },
        { typeid: 7, name: 'сундук-30',           level: '30',        type: 'usual' },
        { typeid: 7, name: 'сундук-35',           level: '35',        type: 'usual' },
        { typeid: 7, name: 'сундук-40',           level: '40',        type: 'usual' },
        { typeid: 7, name: 'сундук-45',           level: '45',        type: 'usual' },
        { typeid: 7, name: 'сундук-50',           level: '50',        type: 'usual' },
        { typeid: 7, name: 'сундук-55',           level: '55',        type: 'usual' },

        // ------------------------------------------------------------------
        // Императорские (typeid 9) — 130
        // ------------------------------------------------------------------
        { typeid: 9, name: 'большие ассирийские игры',  level: '20',        type: 'all'   },
        { typeid: 9, name: 'большие весперовы игры',    level: '25',        type: 'usual' },
        { typeid: 9, name: 'большие галльские игры',    level: '20',        type: 'usual' },
        { typeid: 9, name: 'большие игры бахуса',       level: '40',        type: 'all'   },
        { typeid: 9, name: 'большие игры дианы',        level: '55',        type: 'usual' },
        { typeid: 9, name: 'большие игры дискордии',    level: '50',        type: 'all'   },
        { typeid: 9, name: 'большие игры кентавра',     level: '50',        type: 'usual' },
        { typeid: 9, name: 'большие игры копты',        level: '55',        type: 'all'   },
        { typeid: 9, name: 'большие игры мании',        level: '15',        type: 'usual' },
        { typeid: 9, name: 'большие игры минервы',      level: '30',        type: 'usual' },
        { typeid: 9, name: 'большие игры поллукса',     level: '50',        type: 'all'   },
        { typeid: 9, name: 'большие игры салации',      level: '40',        type: 'usual' },
        { typeid: 9, name: 'большие игры теллуры',      level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'большие игры фавна',        level: '50-55',     type: 'usual' },
        { typeid: 9, name: 'большие игры фавония',      level: '10',        type: 'usual' },
        { typeid: 9, name: 'большие игры фортуны',      level: 'unlimited', type: 'all'   },
        { typeid: 9, name: 'большие игры цереры',       level: '40',        type: 'usual' },
        { typeid: 9, name: 'большие игры ювенты',       level: '30',        type: 'all'   },
        { typeid: 9, name: 'большой турнир геркулеса',  level: '25',        type: 'usual' },
        { typeid: 9, name: 'игры авроры',               level: 'unlimited', type: 'all'   },
        { typeid: 9, name: 'игры адриана',              level: '45',        type: 'all'   },
        { typeid: 9, name: 'игры аквилона',             level: '30',        type: 'all'   },
        { typeid: 9, name: 'игры ангитии',              level: '45',        type: 'all'   },
        { typeid: 9, name: 'игры аполлона',             level: '15',        type: 'usual' },
        { typeid: 9, name: 'игры ардуинны',             level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'игры атласа',               level: '30',        type: 'usual' },
        { typeid: 9, name: 'игры ауры',                 level: '20',        type: 'all'   },
        { typeid: 9, name: 'игры беллоны',              level: '25',        type: 'usual' },
        { typeid: 9, name: 'игры венеры',               level: '50',        type: 'usual' },
        { typeid: 9, name: 'игры весталии',             level: '30',        type: 'usual' },
        { typeid: 9, name: 'игры викингов',             level: '12',        type: 'all'   },
        { typeid: 9, name: 'игры виналии',              level: '45',        type: 'all'   },
        { typeid: 9, name: 'игры гарпий',               level: '8',         type: 'all'   },
        { typeid: 9, name: 'игры гебы',                 level: '35',        type: 'usual' },
        { typeid: 9, name: 'игры гераса',               level: '45',        type: 'usual' },
        { typeid: 9, name: 'игры гета',                 level: '40',        type: 'usual' },
        { typeid: 9, name: 'игры дианы',                level: '45',        type: 'all'   },
        { typeid: 9, name: 'игры дромедарии',           level: '60',        type: 'all'   },
        { typeid: 9, name: 'игры коммода',              level: '50',        type: 'all'   },
        { typeid: 9, name: 'игры купидона',             level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'игры леды',                 level: '55',        type: 'usual' },
        { typeid: 9, name: 'игры либера',               level: '65',        type: 'all'   },
        { typeid: 9, name: 'игры мании',                level: '5',         type: 'all'   },
        { typeid: 9, name: 'игры матралии',             level: '50',        type: 'usual' },
        { typeid: 9, name: 'игры минотавра',            level: '45',        type: 'usual' },
        { typeid: 9, name: 'игры наяды',                level: 'unlimited', type: 'all'   },
        { typeid: 9, name: 'игры нептуна',              level: '20-25',     type: 'all'   },
        { typeid: 9, name: 'игры нереиды',              level: '60',        type: 'usual' },
        { typeid: 9, name: 'игры пандоры',              level: '8',         type: 'usual' },
        { typeid: 9, name: 'игры паралии',              level: '35',        type: 'all'   },
        { typeid: 9, name: 'игры плутона',              level: '55-60',     type: 'usual' },
        { typeid: 9, name: 'игры понтуса',              level: '55',        type: 'usual' },
        { typeid: 9, name: 'игры римского флота',       level: '65',        type: 'all'   },
        { typeid: 9, name: 'игры салюс',                level: '30',        type: 'all'   },
        { typeid: 9, name: 'игры сатурна',              level: 'unlimited', type: 'all'   },
        { typeid: 9, name: 'игры сильвана',             level: '15-20',     type: 'all'   },
        { typeid: 9, name: 'игры соля',                 level: '5-8',       type: 'all'   },
        { typeid: 9, name: 'игры траяна',               level: '45',        type: 'usual' },
        { typeid: 9, name: 'игры фавна',                level: '15',        type: 'all'   },
        { typeid: 9, name: 'игры фидес',                level: '20',        type: 'usual' },
        { typeid: 9, name: 'игры флоры',                level: '50',        type: 'usual' },
        { typeid: 9, name: 'игры фортуны',              level: '40',        type: 'all'   },
        { typeid: 9, name: 'игры цезаря',               level: '40',        type: 'usual' },
        { typeid: 9, name: 'игры целума',               level: '40',        type: 'usual' },
        { typeid: 9, name: 'игры эгерии',               level: '55',        type: 'usual' },
        { typeid: 9, name: 'игры ювенты',               level: '10',        type: 'all'   },
        { typeid: 9, name: 'игры юстиции',              level: '30',        type: 'all'   },
        { typeid: 9, name: 'малые игры весталии',       level: '20',        type: 'usual' },
        { typeid: 9, name: 'малые игры единорога',      level: '8',         type: 'usual' },
        { typeid: 9, name: 'малые игры майи',           level: '8',         type: 'all'   },
        { typeid: 9, name: 'малые игры матралии',       level: '40',        type: 'all'   },
        { typeid: 9, name: 'малые игры сатурна',        level: '45',        type: 'usual' },
        { typeid: 9, name: 'малый турнир пегаса',       level: '10',        type: 'usual' },
        { typeid: 9, name: 'марсовы игры',              level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'римский скорпион',          level: '60',        type: 'all'   },
        { typeid: 9, name: 'терентинские игры',         level: '45-50',     type: 'usual' },
        { typeid: 9, name: 'троянские игры',            level: '15',        type: 'usual' },
        { typeid: 9, name: 'турнир ангероны',           level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир аписа',              level: '50',        type: 'all'   },
        { typeid: 9, name: 'турнир беллоны',            level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир боевого слона',      level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'турнир венеры',             level: '10',        type: 'usual' },
        { typeid: 9, name: 'турнир вергилия',           level: '25',        type: 'all'   },
        { typeid: 9, name: 'турнир вулкана',            level: '30',        type: 'usual' },
        { typeid: 9, name: 'турнир гальба',             level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир грифона',            level: '5',         type: 'usual' },
        { typeid: 9, name: 'турнир дианы',              level: '30',        type: 'all'   },
        { typeid: 9, name: 'турнир дидоны',             level: '65',        type: 'usual' },
        { typeid: 9, name: 'турнир диес',               level: '20',        type: 'usual' },
        { typeid: 9, name: 'турнир золотое руно',       level: '55',        type: 'all'   },
        { typeid: 9, name: 'турнир камены',             level: '55',        type: 'usual' },
        { typeid: 9, name: 'турнир кардеи',             level: '25',        type: 'usual' },
        { typeid: 9, name: 'турнир карна',              level: '40-45',     type: 'usual' },
        { typeid: 9, name: 'турнир кентавра',           level: '8',         type: 'all'   },
        { typeid: 9, name: 'турнир клавдия',            level: '10-15',     type: 'all'   },
        { typeid: 9, name: 'турнир марсово поле',       level: '55',        type: 'all'   },
        { typeid: 9, name: 'турнир марциала',           level: '15',        type: 'all'   },
        { typeid: 9, name: 'турнир медузы',             level: '25',        type: 'all'   },
        { typeid: 9, name: 'турнир меркурия',           level: '20',        type: 'all'   },
        { typeid: 9, name: 'турнир музы',               level: '20',        type: 'usual' },
        { typeid: 9, name: 'турнир нерона',             level: '25-30',     type: 'usual' },
        { typeid: 9, name: 'турнир опсы',               level: '10',        type: 'all'   },
        { typeid: 9, name: 'турнир опы',                level: '55',        type: 'usual' },
        { typeid: 9, name: 'турнир пандоры',            level: '35-40',     type: 'usual' },
        { typeid: 9, name: 'турнир пегаса',             level: '30',        type: 'usual' },
        { typeid: 9, name: 'турнир плутона',            level: '15',        type: 'all'   },
        { typeid: 9, name: 'турнир помпилия',           level: '15',        type: 'usual' },
        { typeid: 9, name: 'турнир прозерпины',         level: '20',        type: 'usual' },
        { typeid: 9, name: 'турнир протея',             level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир психеи',             level: '60',        type: 'usual' },
        { typeid: 9, name: 'турнир розалии',            level: '45',        type: 'usual' },
        { typeid: 9, name: 'турнир салюс',              level: '25',        type: 'all'   },
        { typeid: 9, name: 'турнир сатира',             level: '40',        type: 'usual' },
        { typeid: 9, name: 'турнир сатурна',            level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир селены',             level: '15',        type: 'usual' },
        { typeid: 9, name: 'турнир скарабея',           level: '65',        type: 'usual' },
        { typeid: 9, name: 'турнир славной охоты',      level: '65',        type: 'usual' },
        { typeid: 9, name: 'турнир соколиной охоты',    level: '20',        type: 'all'   },
        { typeid: 9, name: 'турнир теллуры',            level: '60',        type: 'usual' },
        { typeid: 9, name: 'турнир терпсихоры',         level: '10',        type: 'all'   },
        { typeid: 9, name: 'турнир тиберия',            level: '35',        type: 'all'   },
        { typeid: 9, name: 'турнир феба',               level: '35',        type: 'all'   },
        { typeid: 9, name: 'турнир феникса',            level: '20',        type: 'usual' },
        { typeid: 9, name: 'турнир флоры',              level: '30-35',     type: 'usual' },
        { typeid: 9, name: 'турнир химеры',             level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир циклопа',            level: 'unlimited', type: 'usual' },
        { typeid: 9, name: 'турнир эквирии',            level: '40',        type: 'all'   },
        { typeid: 9, name: 'турнир эллисы',             level: '35',        type: 'usual' },
        { typeid: 9, name: 'турнир эскулапа',           level: '25',        type: 'usual' },
        { typeid: 9, name: 'турнир юноны',              level: '10',        type: 'usual' },
        { typeid: 9, name: 'турнир юпитера',            level: '25',        type: 'all'   },

        // ------------------------------------------------------------------
        // Смешанные (typeid 13) — 28
        // ------------------------------------------------------------------
        { typeid: 13, name: 'ассирийские игры',      level: '35',        type: 'all'   },
        { typeid: 13, name: 'большие игры селены',   level: 'unlimited', type: 'usual' },
        { typeid: 13, name: 'галльские игры',        level: '20',        type: 'usual' },
        { typeid: 13, name: 'игры волупии',          level: '25',        type: 'usual' },
        { typeid: 13, name: 'игры дискордии',        level: '30',        type: 'usual' },
        { typeid: 13, name: 'игры марса',            level: '50',        type: 'usual' },
        { typeid: 13, name: 'игры меркурия',         level: '40',        type: 'usual' },
        { typeid: 13, name: 'игры муты',             level: '10',        type: 'all'   },
        { typeid: 13, name: 'игры парки',            level: '12',        type: 'all'   },
        { typeid: 13, name: 'игры поллукса',         level: '8',         type: 'all'   },
        { typeid: 13, name: 'игры тациты',           level: '35',        type: 'usual' },
        { typeid: 13, name: 'капитолийские игры',    level: '40',        type: 'all'   },
        { typeid: 13, name: 'квиритский турнир',     level: '30',        type: 'all'   },
        { typeid: 13, name: 'пунические войны',      level: '20',        type: 'all'   },
        { typeid: 13, name: 'триумвират',            level: '25',        type: 'all'   },
        { typeid: 13, name: 'турнир аполлона',       level: 'unlimited', type: 'all'   },
        { typeid: 13, name: 'турнир вертумна',       level: '8',         type: 'usual' },
        { typeid: 13, name: 'турнир квирина',        level: '15',        type: 'usual' },
        { typeid: 13, name: 'турнир конкордии',      level: '10',        type: 'usual' },
        { typeid: 13, name: 'турнир копты',          level: '15',        type: 'all'   },
        { typeid: 13, name: 'турнир минервы',        level: '55',        type: 'usual' },
        { typeid: 13, name: 'турнир нерва',          level: '50',        type: 'all'   },
        { typeid: 13, name: 'турнир нериены',        level: '55',        type: 'all'   },
        { typeid: 13, name: 'турнир оркуса',         level: '45',        type: 'usual' },
        { typeid: 13, name: 'турнир сомна',          level: '45',        type: 'all'   },
        { typeid: 13, name: 'турнир спартака',       level: '3',         type: 'usual' },
        { typeid: 13, name: 'турнир фонса',          level: '5',         type: 'usual' },
        { typeid: 13, name: 'турнир януса',          level: '5',         type: 'usual' }
    ]
};